name: "Build library"

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - run: dotnet build -c Release

      - uses: actions/upload-artifact@v4
        with:
          path: '**/Release/**/*.dll'
